package constant

const AUTH_WAIT = -1
const MERCHANT_AUTH_ING = 1
const MERCHANT_AUTH_PASS = 2
const MERCHANT_AUTH_FAILED = 3
const OPEN_BANK_ACCOUNT_ING = 4
const OPEN_BANK_ACCOUNT_SUCCESS = 5
const OPEN_BANK_ACCOUNT_FAILED = 6

const CHECKING = 1
const CHECK_PASS = 2
const CHECK_FAILED = 3
const WAIT_COMPLETE = 4
const MANUAL_REVIEW = 99
const N0_CHECKED = -1
